### ISSUE TITLE
Translations using Weblate

### ISSUE THREAD

**Issue by Findus23** [Romain/Matomo-IP-to-Company#11]
Hello,

Lukas from Matomo team here. We are currently in the process of moving our translations from Transifex to Weblate (https://github.com/matomo-org/matomo/issues/17907).
As Weblate makes it easier to add a git repository as a component and merge back updated translations via pull requests, I thought it would be great if more plugins in Matomo were available in the users languages if someone is interested in translating them.

If you are interested in adding your plugin, simply comment here, and I'll help you with the setup.

**Comment by Romain** [comment]
Hi @Findus23 ,

Thanks for reaching out to me.
This plugin is already [available in 5 languages](https://github.com/Romain/Matomo-IP-to-Company/tree/master/lang), but if there's anything to do to have the plugin tracked on Weblate, I'd happy to move in this direction.
Let me know what has to be done.

Romain
