### ISSUE TITLE
Archiving triggered with scheduled tasks no longer work

### ISSUE THREAD

**Issue by Starker3** [Romain/Matomo-IP-to-Company#12]
There has been a recent update to how Matomo scheduled tasks can function. In https://github.com/matomo-org/matomo/issues/17976 
some additional checks were added to stop scheduled tasks from triggering archiving.
(This was included in the recent 4.6.0 release)

From my understanding of how this plugin functions, it uses the scheduled tasks to archive its reports (Instead of being archived during the normal archiving process).

Recently we had some users that experienced issues around this. For example, when a user defines a maximum number of concurrent archivers, Matomo will still trigger any scheduled tasks that are set to execute. For large servers this can take some time, if additional archivers start and then immediately exit because it detects that the maximum number of archivers are already running, then again it triggers the scheduled tasks.

For example, we would see something like this in the archive logs:
```
INFO [2021-11-30 06:15:02] 289292  START
INFO [2021-11-30 06:15:02] 289292  Starting Matomo reports archiving...
INFO [2021-11-30 06:15:02] 289292  Archiving will stop now because 40 archivers are already running and max 2 are supposed to run at once.
INFO [2021-11-30 06:15:02] 289292  Reached maximum concurrent archivers allowed (2), aborting run.
INFO [2021-11-30 06:15:02] 289292  ---------------------------
INFO [2021-11-30 06:15:02] 289292  SCHEDULED TASKS
INFO [2021-11-30 06:15:02] 289292  Starting Scheduled tasks... 
INFO [2021-11-30 06:15:02] 289292  Scheduler: executing task Piwik\Plugins\CustomJsTracker\Tasks.updateTracker...
INFO [2021-11-30 06:15:02] 289292  Scheduler: finished. Time elapsed: 0.015s
INFO [2021-11-30 06:15:02] 289292  Scheduler: executing task Piwik\Plugins\TagManager\Tasks.regenerateReleasedContainers...
INFO [2021-11-30 06:15:33] 289292  Scheduler: finished. Time elapsed: 30.912s
INFO [2021-11-30 06:15:33] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_51...
INFO [2021-11-30 06:17:46] 289292  Scheduler: finished. Time elapsed: 132.869s
INFO [2021-11-30 06:17:46] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_52...
INFO [2021-11-30 06:17:46] 289292  Scheduler: finished. Time elapsed: 0.056s
INFO [2021-11-30 06:17:46] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_53...
INFO [2021-11-30 06:24:35] 289049  Scheduler: finished. Time elapsed: 1442.608s
INFO [2021-11-30 06:24:35] 289049  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_85...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 524.222s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_54...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 0.116s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_58...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 0.046s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_59...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 0.041s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_67...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 0.039s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_69...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 0.040s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_71...
INFO [2021-11-30 06:26:30] 289292  Scheduler: finished. Time elapsed: 0.047s
INFO [2021-11-30 06:26:30] 289292  Scheduler: executing task Piwik\Plugins\IPtoCompany\Tasks.getListOfCompaniesThatVisitedWebsiteYesterday_73...
INFO [2021-11-30 06:30:02] 289545  ---------------------------
```

This can lead to a very high number of concurrently running archivers that are all trying to process IPtoCompany reports:
`Archiving will stop now because 40 archivers are already running and max 2 are supposed to run at once.` 

There is a possible workaround in the linked issue, but we would recommend changing the archiving behaviour so that it doesn't need to be triggered with a scheduled task.

**Comment by Romain** [comment]
Hi @Starker3,

Thanks for raising this point.

You're right, I'm using the schedule feature to [generate the reports once a day](https://github.com/Romain/Matomo-IP-to-Company/commit/31f3a3fff58ab8e26973c72dbd3cee7ee9f4fe55).

I read your discussion with @tsteur. Does PR #16 corresponds to what you advised?

**Comment by tsteur** [comment]
I haven't tested it @Romain but it looks to me that this could work 👍  

It's also what was there initially https://github.com/matomo-org/matomo/pull/18101/files#diff-f41c275e883996b8b69cb765b1818e12e82cbe034e648bc3f7d03610cc7abad1L625

**Comment by Romain** [comment]
@tsteur I just merged the corresponding PR and created a new version.
