### ISSUE TITLE
E-mail delivery although not checked

### ISSUE THREAD

**Issue by Monschder** [Romain/Matomo-IP-to-Company#3]
**Describe the bug**
I receive  every morning an email for every website after the 0.3.0 update.

**To Reproduce**
Personal settings > Subscribe to ... is not checked

**Expected behavior**
No email reports.

**Screenshots**
![SCREEN_2020-03-06_081838](https://user-images.githubusercontent.com/18714880/76061128-2a1b2d00-5f83-11ea-809c-acd224cb31e4.jpg)

Btw: Great plugin - I am a new user but it looks great for our requirements

**Comment by Monschder** [comment]
... and the database setting for 
IPtoCompany | subscribedToEmailReport | 0

is 0.

**Comment by Romain** [comment]
Thanks for this follow-up @Monschder.
I'll dig into this bug and let you know as soon as I get a solution.
Btw, Have you tried updating the plugin to the actual version, 0.3.2?
Romain

**Comment by Romain** [comment]
I think that I got it. I was sending the emails to all the superusers, even though they haven't checked the option.
0.3.3 should fix this.

**Comment by Romain** [comment]
Edit: I had to bump the version, it's 0.3.5, but this should be fixed anyway. ;)

**Comment by Monschder** [comment]
THX

**Comment by Romain** [comment]
You're welcome. Let me know if this is good to you.

**Comment by Monschder** [comment]
Three days and no email - it worked well.

Merci beaucoup!

**Comment by Romain** [comment]
You're welcome ! ;)
