### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by gemma-leigh** [Romain/Matomo-IP-to-Company#4]
When going to Visitors/Companies the following error shows up:

- _Exception: {"status":400}_

This also shows up in the dashboard of Matomo:

- _WARNING: /home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/API.php(141): Warning - gethostbyaddr(): Address is not a valid IPv4 or IPv6 address - Matomo 3.13.5

(Module: IPtoCompany, Action: getCompanies, Method: IPtoCompany.getCompanies, In CLI mode: false)_

We did add the IPinfo.io access token and have uninstalled and re-installed the plugin a few times and still get the error.

**Comment by Romain** [comment]
Hi @gemma-leigh ,

I tried to reproduce this bug but I couldn't.
I tried with Matomo 3.13.5 / PHP 7.3.15, and Matomo 3.13.3 / PHP 7.4.
Can you tell me what's your PHP version?

**Comment by gemma-leigh** [comment]
Hey @Romain we are running Matomo 3.13.5, and have tried PHP 5.4 to PHP 7.4.5 and all give same error.  Data in MySQL looks fine, must be some kind of reverse looking issue or something?

Here's what the log viewer shows:

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#14 /home/secure/public_html/analytics.myserver.com/core/FrontController.php(165): Piwik\FrontController->doDispatch('IPtoCompany', 'getCompanies', Array)

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#12 [internal function]: Piwik\Plugins\CoreHome\Controller->renderReportWidget(Object(Piwik\Plugins\IPtoCompany\Reports\GetCompanies))

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#4 [internal function]: Piwik\Plugins\IPtoCompany\API->getCompanies('1', 'month', 'today', false)

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#3 /home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/API.php(78): Piwik\Plugins\IPtoCompany\API->getIPDetails('23.115.10.156 |...', Array, Array)

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#2 /home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/API.php(172): Piwik\Plugins\IPtoCompany\API->getCompanyDetails('23.115.10.156 |...')

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#1 /home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/API.php(198): Piwik\Plugins\IPtoCompany\libraries\IPInfo->getDetails('23.115.10.156 |...')

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	#0 /home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/Libraries/IPInfo.php(50): Piwik\Plugins\IPtoCompany\libraries\IPInfo->getRequestDetails('23.115.10.156 |...')

ERROR	CoreHome	2020-05-19 18:40:45 UTC	0c224	"Failed to get data from API: /home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/Libraries/IPInfo.php(117): Exception: {""status"":400}"

WARNING	IPtoCompany	2020-05-19 18:40:45 UTC	0c224	/home/secure/public_html/analytics.myserver.com/plugins/IPtoCompany/API.php(141): Warning - gethostbyaddr(): Address is not a valid IPv4 or IPv6 address - Matomo 3.13.5

**Comment by Romain** [comment]
Thanks for these extra details @gemma-leigh . I think that I got it.
For any reason, the IP that Matomo returned to the plugin was not a valid IP address: `'23.115.10.156 |...'`.  Valid IP should be `'23.115.10.156'`.

I pushed [a fix](https://github.com/Romain/Matomo-IP-to-Company/commit/1ac4217739ded2db4179ebb030c2d99e24c415d1) which adds a condition to check for the validity of the IP address before proceeding the request to get the name of the company.

Let me know if this solves your problem.
I would be curious to get the whole IP though, to understand how it is formatted and why Matomo returns it like this, if you don't mind and if you can get it.

**Comment by gemma-leigh** [comment]
Great news @Romain - the new update fixed the issue.  Thanks so much for taking time to solve this.

**Comment by Romain** [comment]
You're welcome. ;)
