### ISSUE TITLE
Problem after removing the IPinfo.io token

### ISSUE THREAD

**Issue by jb-ks** [Romain/Matomo-IP-to-Company#5]
I used the plugin for some month without problems. I put in my (free) IPinfo token to check if there is a difference in the quality.

After removing the token, the Plugin stopped working. 

At Visitors —> Companies I get an error message:   IPinfo request quota exceeded.

Ist seems, that the Plugin still tries to use IPInfo.io, but with no valid token.

Deleting and reinstalling the Plugin does not help.

**Comment by Romain** [comment]
Thanks @jb-ks for pointing that out.
I pushed a fix in version [0.4.3](https://github.com/Romain/Matomo-IP-to-Company/releases/tag/0.4.3) which prevents the use of IPInfo if no token has been set.
Can you confirm to me that it is better now?

**Comment by jb-ks** [comment]
Romain,

thanks for the update. The Plugin now works perfect again.

Thanks
Jan

**Comment by jb-ks** [comment]
Oh, there is one degression now. In the backend a warining is displayed:

WARNING: Sorting the API method &quot;Live.getLastVisitDetails&quot; by column is currently not supported. To avoid this warning remove the URL parameter &quot;filter_sort_column&quot; from your API request. (Module: API, Action: getCompanies, Method: Live.getLastVisitsDetails, In CLI mode: false)

But it seems, that the functionality of Matomo is not affected.

Best regards
Jan

**Comment by Romain** [comment]
Thanks for mentioning this Warning Jan.
Actually, it has been there since the very beginning. I just didn't manage to get rid off it for now. I don't use the `filter_sort_column` parameter in the API request, so I'm not sure why I get this warning.
Regarding your initial problem which was the fact that the plugin didn't work without IPInfo token, is it better now?

**Comment by jb-ks** [comment]
Yes, the functionality of your plugin is fine now.  :-)

**Comment by Romain** [comment]
Cool, thanks!
I'll keep an eye on this warning to see if I can find a solution... ;)
