### ISSUE TITLE
Pagination missing in results table, generates a warning

### ISSUE THREAD

**Issue by mhh515** [Romain/Matomo-IP-to-Company#8]
We have a problem with the IPtoCompany results table; it does not show “Next >” although there are more than 5 results
(we can see it if we select more “Rows to display”):

![iptocompnay_pagination](https://user-images.githubusercontent.com/72019879/94427605-a7142b00-018f-11eb-81b8-68e036cd9bad.jpg)

> WARNING: Sorting the API method &quot;Live.getLastVisitDetails&quot; by column is currently not supported. To avoid this warning remove the URL parameter &quot;filter_sort_column&quot; from your API request. (Module: API, Action: getCompanies, Method: Live.getLastVisitsDetails, In CLI mode: false)

The warning also _seems_ to disable the plugin in Matomo.

**Comment by Romain** [comment]
Hi @mhheene,
Thanks for letting me know about this bug.
I'll investigate to see what can be the cause. Could you give me the version number of your matomo installation?

**Comment by mhh515** [comment]
Hi @Romain , we are currently using Matomo 3.14.0 (3.14.1 is the latest but we haven't upgraded yet), and the IPtoCompany plugin version is 0.4.5.

**Comment by Romain** [comment]
Ok, thanks, I'll check this out.

**Comment by Romain** [comment]
Hi @mhheene, version [0.4.6](https://github.com/Romain/Matomo-IP-to-Company/releases/tag/0.4.6) fixes the pagination issue.
I also prepared a release compatible to Matomo 4.x, which includes this fix.

**Comment by mhh515** [comment]
Thanks a lot, @Romain

**Comment by Romain** [comment]
@mhheene You're welcome!

**Comment by mhh515** [comment]
@Romain , have you submitted the latest release to the Matomo marketplace yet? I.e., can I download it from there, or should I use the version here on BitBucket? There are two versions now, 0.4.6 and 1.0.1; which one should I use? Thanks!

**Comment by Romain** [comment]
@mhheene Both versions are available, it depends on your setup. 0.4.6 is for Matomo 3.x and 1.0.1 is for 4.x.
The easiest way to update (or install) this plugin is to go in the admin section of Matomo and use the components tab. You should be able to install or update it from there.
