### ISSUE TITLE
 'Exception: {"status":400}" when installing the plugin with matomo 3.14.1

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [Romain/Matomo-IP-to-Company#9]
**Describe the bug**

I installed Ip2 to company on Matomo version: 3.14.1

and i trigger the bug mentioned in https://github.com/Romain/Matomo-IP-to-Company/issues/4

**To Reproduce**
1. install ip2company
2. Click on Visitors/Companies
3. Get the 'Exception: {"status":400}"

**Expected behavior**

See a list of companies like in the screenshot in the documentation

**Screenshots**

![ip2comapny-bugs](https://user-images.githubusercontent.com/243766/104244926-a912a900-5463-11eb-9129-06cbc5759fa2.png)

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser [Firefox]
 - Version [78.6.1esr]

**Additional context**

**Comment by Romain** [comment]
Hi @bilbo-the-hobbit, thanks for letting me know about this bug.
Could you paste here the logs generated by this error?
To do so, please install the [LogViewer plugin](https://plugins.matomo.org/LogViewer), activate it, go again on the page that generates an error, and then, copy the logs from the log viewer in the admin.

**Comment by Romain** [comment]
Can you also tell me which version of the plugin has been installed?

**Comment by bilbo-the-hobbit** [comment]
i installed IPtoCompany 4.0.3 and then matomo suggested to upgrade to 4.0.6.

I installed logviewer but i got not log into Logviewer after going forth and back clicking on Visitors/companies ?

my setup is a follow, i connect to my sso portal that redirect me to matomo with http headers. 

looking a my log i found this see the file attatched

[ip2company-bug.txt](https://github.com/Romain/Matomo-IP-to-Company/files/5819484/ip2company-bug.txt)

**Comment by Romain** [comment]
Thanks for this file @bilbo-the-hobbit, it helped.
I published new versions of the plugin (0.4.7 and 1.0.2). Could you try them and let me know if it fixed the bug?

**Comment by bilbo-the-hobbit** [comment]
hello @Romain,

i just upgrade and it seems to work fine now

Cheers

**Comment by Romain** [comment]
Thanks @bilbo-the-hobbit
